const app = document.querySelector('#app');
const state = { actor:null, csrf:null, adminTab:true, data:{}, wizard:{step:1, product:null, customerName:'',phone:'',challengeId:null,evidenceId:null,devOtp:null} };

const esc = (v='') => String(v).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num = v => new Intl.NumberFormat('vi-VN').format(Number(v||0));
function toast(message){ const el=document.createElement('div');el.className='toast';el.textContent=message;document.body.append(el);setTimeout(()=>el.remove(),4200); }

async function api(path,{method='GET',body,headers={}}={}){
  const options={method,headers:{...headers}};
  if(state.csrf && !['GET','HEAD'].includes(method)) options.headers['X-CSRF-Token']=state.csrf;
  if(body!==undefined && !(body instanceof FormData)){options.headers['Content-Type']='application/json';options.body=JSON.stringify(body)} else if(body instanceof FormData) options.body=body;
  const res=await fetch(path,options); const type=res.headers.get('content-type')||'';
  if(!type.includes('application/json')){ if(!res.ok) throw new Error(`HTTP ${res.status}`); return res; }
  const data=await res.json(); if(!res.ok||!data.ok){ const err=new Error(data?.error?.message||'Có lỗi xảy ra');err.code=data?.error?.code;throw err; } return data.data;
}

async function detectSession(){
  try{const me=await api('/api/admin/auth/me');state.actor=me;state.csrf=me.csrfToken;return;}catch{}
  try{const me=await api('/api/ctv/me');state.actor=me;state.csrf=me.csrfToken;return;}catch{}
  const token=new URLSearchParams(location.search).get('zalo_token');
  if(token){try{const result=await api('/api/ctv/auth/zalo',{method:'POST',body:{token}});state.actor=result.actor;state.csrf=result.actor.csrfToken;history.replaceState({},'',location.pathname);return;}catch(e){toast(e.message)}}
}

function loginView(){
  app.innerHTML=`<main class="login-wrap"><section class="card login-card"><div class="brand"><div class="brandmark">M</div><div><div>MẫuMới</div><div class="small muted">CTV phát mẫu • Khách hàng mới</div></div></div><h1>Đăng nhập</h1><div class="tabs"><button class="tab ${state.adminTab?'active':''}" id="tab-admin">Admin</button><button class="tab ${!state.adminTab?'active':''}" id="tab-ctv">CTV</button></div><div id="login-form"></div></section></main>`;
  document.querySelector('#tab-admin').onclick=()=>{state.adminTab=true;loginView()};document.querySelector('#tab-ctv').onclick=()=>{state.adminTab=false;loginView()};
  const box=document.querySelector('#login-form');
  if(state.adminTab){box.innerHTML=`<form id="admin-login"><div class="field"><label>Email</label><input class="input" name="email" type="email" required autocomplete="username"></div><div class="field"><label>Mật khẩu</label><input class="input" name="password" type="password" required autocomplete="current-password"></div><button class="btn" style="width:100%">Đăng nhập Admin</button></form>`;document.querySelector('#admin-login').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{const r=await api('/api/admin/auth/login',{method:'POST',body:{email:f.get('email'),password:f.get('password')}});state.actor=r.actor;state.csrf=r.actor.csrfToken;location.hash='#/admin/dashboard';render()}catch(err){toast(err.message)}}}
  else{box.innerHTML=`<form id="ctv-login"><div class="field"><label>Mã CTV (chỉ dùng pilot/dev)</label><input class="input" name="code" placeholder="CTV001" required></div><button class="btn" style="width:100%">Đăng nhập CTV</button><p class="small muted">Production Zalo dùng token do Mini App gửi về endpoint <code>/api/ctv/auth/zalo</code>. Dev login tự động bị từ chối nếu server không bật cờ pilot.</p></form>`;document.querySelector('#ctv-login').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{const r=await api('/api/ctv/auth/dev',{method:'POST',body:{code:f.get('code')}});state.actor=r.actor;state.csrf=r.actor.csrfToken;location.hash='#/ctv/home';render()}catch(err){toast(err.message)}}}
}

const adminNav=[['dashboard','Tổng quan'],['ctv','CTV'],['products','Sản phẩm'],['inventory','Kho'],['customers','Khách hàng'],['distributions','Phát mẫu'],['reconciliation','Đối soát'],['import-export','Import / Export'],['audit','Audit']];
const ctvNav=[['home','Trang chủ'],['distribute','Phát mẫu'],['history','Lịch sử'],['reconciliation','Đối soát']];
function shell(content,active){
  const isAdmin=state.actor.type==='ADMIN'; const nav=isAdmin?adminNav:ctvNav;
  app.innerHTML=`<div class="shell"><header class="topbar"><div class="brand"><div class="brandmark">M</div><span>MẫuMới</span></div><div class="row"><span class="small muted">${esc(state.actor.name||state.actor.code)}</span><button class="btn secondary" id="logout">Thoát</button></div></header><div class="layout"><aside class="sidebar">${nav.map(([id,label])=>`<button class="navbtn ${active===id?'active':''}" data-nav="${id}">${esc(label)}</button>`).join('')}</aside><main class="content">${content}</main></div><nav class="mobile-bottom">${nav.slice(0,4).map(([id,label])=>`<button data-nav="${id}">${esc(label)}</button>`).join('')}</nav></div>`;
  document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{location.hash=`#/${isAdmin?'admin':'ctv'}/${b.dataset.nav}`;render()});
  document.querySelector('#logout').onclick=async()=>{try{await api(state.actor.type==='ADMIN'?'/api/admin/auth/logout':'/api/ctv/auth/logout',{method:'POST',body:{}})}catch{}state.actor=null;state.csrf=null;location.hash='';render()};
}

function table(headers,rows){ if(!rows.length)return '<div class="empty">Chưa có dữ liệu.</div>'; return `<div class="tablewrap"><table class="table"><thead><tr>${headers.map(h=>`<th>${esc(h.label)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${headers.map(h=>`<td>${h.render?h.render(r):esc(r[h.key]??'')}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`; }
async function load(path,key){ state.data[key]=await api(path); return state.data[key]; }

async function adminDashboard(){ const d=await load('/api/admin/dashboard','dashboard'); shell(`<div class="row between"><div><h1>Tổng quan</h1><p class="muted">Tình hình phân phối mẫu hiện tại.</p></div></div><div class="grid cards">${[['CTV hoạt động',d.activeCtv],['Mẫu đã giao',d.allocated],['Đã phát',d.distributed],['Còn lại',d.remaining],['Khách xác thực',d.verifiedCustomers],['OTP sai hôm nay',d.otpFailures],['Đối soát lệch',d.unresolvedReconciliations]].map(([a,b])=>`<div class="card"><div class="muted small">${a}</div><div class="metric">${num(b)}</div></div>`).join('')}</div><div class="grid" style="grid-template-columns:repeat(auto-fit,minmax(320px,1fr));margin-top:14px"><section class="card"><h3>Top CTV</h3>${table([{label:'CTV',render:r=>`${esc(r.code)} — ${esc(r.name)}`},{label:'Đã phát',key:'distributed'}],d.topCtv)}</section><section class="card"><h3>14 ngày gần nhất</h3>${table([{label:'Ngày',key:'day'},{label:'Đã phát',key:'distributed'}],d.trend)}</section></div>`,'dashboard'); }

async function adminCtv(){ const rows=await load('/api/admin/collaborators','ctv'); shell(`<div class="row between"><div><h1>CTV</h1><p class="muted">Quản lý cộng tác viên phát mẫu.</p></div><button class="btn" id="new-ctv">+ Thêm CTV</button></div><section class="card">${table([{label:'Mã',key:'code'},{label:'Tên',key:'name'},{label:'SĐT',key:'phone'},{label:'Khu vực',key:'area'},{label:'Team',key:'team'},{label:'Trạng thái',render:r=>`<span class="badge ${r.status==='ACTIVE'?'ok':'warn'}">${esc(r.status)}</span>`}],rows)}</section><section class="card" id="ctv-form" style="display:none;margin-top:14px"><h3>Thêm CTV</h3><form id="create-ctv" class="formgrid"><div class="field"><label>Mã</label><input class="input" name="code" required></div><div class="field"><label>Tên</label><input class="input" name="name" required></div><div class="field"><label>SĐT</label><input class="input" name="phone" required inputmode="tel"></div><div class="field"><label>Khu vực</label><input class="input" name="area"></div><div class="field"><label>Team</label><input class="input" name="team"></div><div class="field"><label>Trạng thái</label><select name="status"><option>ACTIVE</option><option>SUSPENDED</option><option>INACTIVE</option></select></div><div class="span2"><button class="btn">Tạo CTV</button></div></form></section>`,'ctv');document.querySelector('#new-ctv').onclick=()=>document.querySelector('#ctv-form').style.display='block';document.querySelector('#create-ctv').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));try{await api('/api/admin/collaborators',{method:'POST',body:f});toast('Đã tạo CTV');adminCtv()}catch(err){toast(err.message)}}; }

async function adminProducts(){ const rows=await load('/api/admin/products','products'); shell(`<div class="row between"><div><h1>Sản phẩm</h1><p class="muted">SKU và chiến dịch mẫu thử.</p></div><button class="btn" id="new-product">+ Thêm sản phẩm</button></div><section class="card">${table([{label:'SKU',key:'sku'},{label:'Tên',key:'name'},{label:'Chiến dịch',key:'campaign_code'},{label:'Trạng thái',key:'status'}],rows)}</section><section class="card" id="product-form" style="display:none;margin-top:14px"><form id="create-product" class="formgrid"><div class="field"><label>SKU</label><input class="input" name="sku" required></div><div class="field"><label>Tên</label><input class="input" name="name" required></div><div class="field"><label>Campaign code</label><input class="input" name="campaignCode" required></div><div class="field"><label>Trạng thái</label><select name="status"><option>ACTIVE</option><option>INACTIVE</option></select></div><div class="span2"><button class="btn">Tạo sản phẩm</button></div></form></section>`,'products');document.querySelector('#new-product').onclick=()=>document.querySelector('#product-form').style.display='block';document.querySelector('#create-product').onsubmit=async e=>{e.preventDefault();try{await api('/api/admin/products',{method:'POST',body:Object.fromEntries(new FormData(e.currentTarget))});toast('Đã tạo sản phẩm');adminProducts()}catch(err){toast(err.message)}}; }

async function adminInventory(){ const [inv,ctv,products]=await Promise.all([api('/api/admin/inventory'),api('/api/admin/collaborators?limit=100'),api('/api/admin/products?limit=100')]); shell(`<div class="row between"><div><h1>Kho CTV</h1><p class="muted">Tồn = giao + điều chỉnh − đã phát.</p></div></div><section class="card"><form id="allocate" class="formgrid"><div class="field"><label>CTV</label><select name="collaboratorId">${ctv.filter(x=>x.status==='ACTIVE').map(x=>`<option value="${esc(x.id)}">${esc(x.code)} — ${esc(x.name)}</option>`).join('')}</select></div><div class="field"><label>Sản phẩm</label><select name="productId">${products.filter(x=>x.status==='ACTIVE').map(x=>`<option value="${esc(x.id)}">${esc(x.sku)} — ${esc(x.name)}</option>`).join('')}</select></div><div class="field"><label>Số lượng</label><input class="input" name="quantity" type="number" min="1" value="10" required></div><div class="field"><label>Tham chiếu</label><input class="input" name="sourceRef" placeholder="Phiếu giao / chiến dịch"></div><div class="span2"><button class="btn">Giao mẫu</button></div></form></section><section class="card" style="margin-top:14px">${table([{label:'CTV',key:'collaborator_code'},{label:'SKU',key:'sku'},{label:'Đã giao',key:'allocated'},{label:'Điều chỉnh',key:'adjustments'},{label:'Đã phát',key:'distributed'},{label:'Còn',render:r=>`<strong>${num(r.available)}</strong>`}],inv)}</section>`,'inventory');document.querySelector('#allocate').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));f.quantity=Number(f.quantity);try{await api('/api/admin/allocations',{method:'POST',body:f});toast('Đã giao mẫu');adminInventory()}catch(err){toast(err.message)}}; }

async function adminSimple(kind,path,headers){ const rows=await load(path,kind); shell(`<h1>${({customers:'Khách hàng',distributions:'Lịch sử phát mẫu',audit:'Audit log'}[kind])}</h1><section class="card">${table(headers,rows)}</section>`,kind); }

async function adminReconciliation(){ const rows=await load('/api/admin/reconciliations','recs'); shell(`<h1>Đối soát</h1><section class="card">${table([{label:'Ngày',key:'business_date'},{label:'CTV',render:r=>`${esc(r.collaborator_code)} — ${esc(r.collaborator_name)}`},{label:'Lệch',key:'absolute_variance'},{label:'Trạng thái',key:'status'},{label:'Thao tác',render:r=>r.status==='SUBMITTED'?`<button class="btn" data-approve="${esc(r.id)}">Duyệt</button> <button class="btn danger" data-reject="${esc(r.id)}">Từ chối</button>`:''}],rows)}</section>`,'reconciliation');document.querySelectorAll('[data-approve]').forEach(b=>b.onclick=()=>reviewRec(b.dataset.approve,'approve'));document.querySelectorAll('[data-reject]').forEach(b=>b.onclick=()=>reviewRec(b.dataset.reject,'reject')); }
async function reviewRec(id,action){try{await api(`/api/admin/reconciliations/${id}/${action}`,{method:'POST',body:{}});toast('Đã cập nhật đối soát');adminReconciliation()}catch(e){toast(e.message)}}

function adminImportExport(){ shell(`<h1>Import / Export</h1><div class="grid" style="grid-template-columns:repeat(auto-fit,minmax(300px,1fr))"><section class="card"><h3>Import CTV CSV</h3><p class="small muted">Header: code,name,phone,area,team,status</p><input id="csv-ctv" type="file" accept=".csv,text/csv"><button class="btn" id="upload-ctv" style="margin-top:10px">Import</button></section><section class="card"><h3>Import phân bổ CSV</h3><p class="small muted">Header: collaborator_code,sku,quantity,source_ref</p><input id="csv-alloc" type="file" accept=".csv,text/csv"><button class="btn" id="upload-alloc" style="margin-top:10px">Import</button></section><section class="card span2"><h3>Export</h3><div class="row">${['collaborators','customers','distributions','inventory','reconciliation'].map(x=>`<a class="btn secondary" href="/api/admin/reports/${x}.csv">${x}.csv</a>`).join('')}</div></section></div>`,'import-export');document.querySelector('#upload-ctv').onclick=()=>uploadCsv('#csv-ctv','/api/admin/collaborators/import');document.querySelector('#upload-alloc').onclick=()=>uploadCsv('#csv-alloc','/api/admin/allocations/import'); }
async function uploadCsv(sel,path){const file=document.querySelector(sel).files[0];if(!file)return toast('Chọn file CSV');try{const res=await fetch(path,{method:'POST',headers:{'X-CSRF-Token':state.csrf,'Content-Type':'text/csv'},body:await file.text()});const data=await res.json();if(!res.ok||!data.ok)throw new Error(data?.error?.message||'Import lỗi');toast(`Import ${data.data.imported} dòng thành công`)}catch(e){toast(e.message)}}

async function ctvHome(){ const [inv,me]=await Promise.all([api('/api/ctv/inventory'),api('/api/ctv/me')]); const total=inv.reduce((s,x)=>s+Number(x.available),0); shell(`<section class="hero"><div class="muted small">Xin chào</div><h1>${esc(me.name)}</h1><p>Bạn còn <strong>${num(total)}</strong> mẫu để phát.</p><button class="btn secondary" id="go-dist">Phát mẫu ngay</button></section><h2>Kho của tôi</h2><section class="card">${table([{label:'SKU',key:'sku'},{label:'Sản phẩm',key:'product_name'},{label:'Đã giao',key:'allocated'},{label:'Đã phát',key:'distributed'},{label:'Còn',render:r=>`<strong>${num(r.available)}</strong>`}],inv)}</section>`,'home');document.querySelector('#go-dist').onclick=()=>{location.hash='#/ctv/distribute';render()}; }

async function ctvDistribute(){ const inv=(await api('/api/ctv/inventory')).filter(x=>Number(x.available)>0); const w=state.wizard;if(!w.product&&inv[0])w.product=inv[0].product_id; const active=inv.find(x=>x.product_id===w.product); shell(`<h1>Phát mẫu</h1><div class="wizard">${['Khách hàng','OTP','Chụp ảnh','Xác nhận','Hoàn tất'].map((x,i)=>`<div class="step ${w.step===i+1?'active':''}">${i+1}. ${x}</div>`).join('')}</div><section class="card" id="wizard-body"></section>`,'distribute');const box=document.querySelector('#wizard-body');
  if(!inv.length){box.innerHTML='<div class="empty">Bạn chưa có mẫu khả dụng.</div>';return}
  if(w.step===1){box.innerHTML=`<h3>1. Thông tin khách hàng</h3><form id="step1"><div class="field"><label>Sản phẩm</label><select name="productId">${inv.map(x=>`<option value="${esc(x.product_id)}" ${x.product_id===w.product?'selected':''}>${esc(x.sku)} — ${esc(x.product_name)} (còn ${num(x.available)})</option>`).join('')}</select></div><div class="field"><label>Tên khách hàng</label><input class="input" name="customerName" required value="${esc(w.customerName)}"></div><div class="field"><label>Số điện thoại</label><input class="input" name="phone" inputmode="tel" required value="${esc(w.phone)}"></div><button class="btn">Kiểm tra & gửi OTP</button></form>`;document.querySelector('#step1').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));w.product=f.productId;w.customerName=f.customerName;w.phone=f.phone;const p=inv.find(x=>x.product_id===w.product);try{const pre=await api('/api/ctv/customers/precheck',{method:'POST',body:{phone:w.phone,productId:w.product}});if(!pre.available)throw new Error('Khách đã nhận mẫu trong chiến dịch này');const otp=await api('/api/otp/request',{method:'POST',body:{phone:w.phone,campaignCode:p.campaign_code}});w.challengeId=otp.challengeId;w.devOtp=otp.devOtp||null;w.step=2;ctvDistribute()}catch(err){toast(err.message)}}}
  else if(w.step===2){box.innerHTML=`<h3>2. Xác thực OTP</h3><p class="muted">OTP đã gửi tới khách hàng. ${w.devOtp?`<span class="badge warn">Pilot OTP: ${esc(w.devOtp)}</span>`:''}</p><form id="step2"><div class="field"><label>OTP 6 số</label><input class="input" name="otp" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" required></div><button class="btn">Xác thực</button></form>`;document.querySelector('#step2').onsubmit=async e=>{e.preventDefault();const otp=new FormData(e.currentTarget).get('otp');try{await api('/api/otp/verify',{method:'POST',body:{challengeId:w.challengeId,otp}});w.step=3;ctvDistribute()}catch(err){toast(err.message)}}}
  else if(w.step===3){box.innerHTML=`<h3>3. Chụp ảnh trực tiếp</h3><label class="camera">📷<br><strong>Chụp ảnh xác nhận phát mẫu</strong><br><span class="small muted">Ảnh JPEG/PNG/WebP, tối đa 8 MB</span><input id="photo" type="file" accept="image/*" capture="environment" required></label><button class="btn" id="upload-photo" style="margin-top:12px">Tải ảnh lên</button>`;document.querySelector('#upload-photo').onclick=async()=>{const file=document.querySelector('#photo').files[0];if(!file)return toast('Bạn phải chụp ảnh');const fd=new FormData();fd.append('photo',file);try{const ev=await api('/api/evidence',{method:'POST',body:fd});w.evidenceId=ev.evidenceId;w.step=4;ctvDistribute()}catch(err){toast(err.message)}}}
  else if(w.step===4){box.innerHTML=`<h3>4. Xác nhận</h3><div class="grid"><div><span class="muted small">Khách</span><div><strong>${esc(w.customerName)}</strong></div></div><div><span class="muted small">SĐT</span><div>${esc(w.phone)}</div></div><div><span class="muted small">Sản phẩm</span><div>${esc(active?.sku||w.product)}</div></div></div><p class="small success-text">✓ OTP đã xác thực & ảnh đã tải.</p><button class="btn" id="confirm-dist">Xác nhận phát 1 mẫu</button>`;document.querySelector('#confirm-dist').onclick=async()=>{const key=`dist_${crypto.randomUUID()}`;try{await api('/api/ctv/distributions',{method:'POST',headers:{'Idempotency-Key':key},body:{customerName:w.customerName,phone:w.phone,productId:w.product,quantity:1,otpChallengeId:w.challengeId,evidenceId:w.evidenceId}});w.step=5;ctvDistribute()}catch(err){toast(err.message)}}}
  else{box.innerHTML=`<div class="empty"><div style="font-size:48px">✅</div><h2>Phát mẫu thành công</h2><p>Giao dịch đã được ghi nhận và đối soát vào kho.</p><button class="btn" id="again">Phát mẫu tiếp</button></div>`;document.querySelector('#again').onclick=()=>{state.wizard={step:1,product:null,customerName:'',phone:'',challengeId:null,evidenceId:null,devOtp:null};ctvDistribute()}}
}

async function ctvHistory(){ const rows=await api('/api/ctv/distributions'); shell(`<h1>Lịch sử phát mẫu</h1><section class="card">${table([{label:'Thời gian',key:'distributed_at'},{label:'SKU',key:'sku'},{label:'Khách',key:'phone_masked'},{label:'SL',key:'quantity'},{label:'Trạng thái',key:'status'}],rows)}</section>`,'history'); }
async function ctvReconciliation(){ const d=await api('/api/ctv/reconciliation/today'); shell(`<div class="row between"><div><h1>Đối soát ${esc(d.businessDate)}</h1><p class="muted">Trạng thái: <span class="badge">${esc(d.status)}</span></p></div></div><section class="card">${d.status!=='OPEN'?'<div class="empty">Đối soát hôm nay đã gửi.</div>':`<form id="rec-form">${d.lines.map((x,i)=>`<div class="card" style="margin:10px 0;background:#fafcff"><strong>${esc(x.sku)} — ${esc(x.productName)}</strong><div class="small muted">Đã giao: ${num(x.assigned)} • Đã phát: ${num(x.distributed)} • Còn hệ thống: ${num(x.currentAvailable)}</div><input type="hidden" name="productId_${i}" value="${esc(x.productId)}"><div class="formgrid"><div class="field"><label>Hoàn</label><input class="input" type="number" min="0" name="returned_${i}" value="0"></div><div class="field"><label>Hỏng</label><input class="input" type="number" min="0" name="damaged_${i}" value="0"></div><div class="field"><label>Tồn cuối ngày</label><input class="input" type="number" min="0" name="closing_${i}" value="${Number(x.currentAvailable)}" required></div><div class="field"><label>Lý do nếu lệch</label><input class="input" name="reason_${i}"></div></div></div>`).join('')}<button class="btn">Gửi đối soát</button></form>`}</section>`,'reconciliation');const form=document.querySelector('#rec-form');if(form)form.onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const lines=d.lines.map((x,i)=>({productId:x.productId,returned:Number(f.get(`returned_${i}`)||0),damaged:Number(f.get(`damaged_${i}`)||0),closing:Number(f.get(`closing_${i}`)||0),reason:f.get(`reason_${i}`)||''}));try{await api('/api/ctv/reconciliation/submit',{method:'POST',body:{lines}});toast('Đã gửi đối soát');ctvReconciliation()}catch(err){toast(err.message)}}; }

async function render(){ if(!state.actor){loginView();return}const parts=(location.hash||`#/${state.actor.type==='ADMIN'?'admin':'ctv'}/${state.actor.type==='ADMIN'?'dashboard':'home'}`).slice(2).split('/');const page=parts[1]||'';try{if(state.actor.type==='ADMIN'){if(page==='dashboard')return adminDashboard();if(page==='ctv')return adminCtv();if(page==='products')return adminProducts();if(page==='inventory')return adminInventory();if(page==='customers')return adminSimple('customers','/api/admin/customers',[{label:'Tên',key:'name'},{label:'SĐT',key:'phone_masked'},{label:'CTV',key:'collaborator_code'},{label:'Tạo lúc',key:'created_at'}]);if(page==='distributions')return adminSimple('distributions','/api/admin/distributions',[{label:'Thời gian',key:'distributed_at'},{label:'CTV',key:'collaborator_code'},{label:'Khách',key:'customer_name'},{label:'SĐT',key:'phone_masked'},{label:'SKU',key:'sku'},{label:'SL',key:'quantity'},{label:'Ảnh',render:r=>`<a href="/api/admin/evidence/${esc(r.evidence_id)}" target="_blank">Xem</a>`}]);if(page==='reconciliation')return adminReconciliation();if(page==='import-export')return adminImportExport();if(page==='audit')return adminSimple('audit','/api/admin/audit',[{label:'Thời gian',key:'created_at'},{label:'Actor',key:'actor_type'},{label:'Action',key:'action'},{label:'Entity',render:r=>`${esc(r.entity_type)} ${esc(r.entity_id||'')}`}]);location.hash='#/admin/dashboard';return render()}else{if(page==='home')return ctvHome();if(page==='distribute')return ctvDistribute();if(page==='history')return ctvHistory();if(page==='reconciliation')return ctvReconciliation();location.hash='#/ctv/home';return render()}}catch(e){if(e.code==='UNAUTHORIZED'){state.actor=null;state.csrf=null;return loginView()}shell(`<section class="card"><h2>Không tải được dữ liệu</h2><p class="danger-text">${esc(e.message)}</p><a class="btn" href="/">Thử lại</a></section>`,page)}}

window.addEventListener('hashchange',render);
await detectSession();render();
